#!/usr/bin/perl

## this script is making reference image links for markdown
## use this in folder with images, just rename "folder" to your folder name
print "Markdown Images reference links, put somewhere in document \n";
opendir(INFILE, "images") || die ("Unable to open directory");
#this line gets rid of . and ..<br>
@files = grep !/^\./, readdir(INFILE);

closedir(INFILE);

foreach $file (sort @files) {

#this was the example for making links from images and make html doc, see original script below
#print ("<font size=\"2\"face=\"arial\"><a href=/owner/$file>$+file</a></font>\n<br>");

print ("[$file]: images\/$file \"$file\"\n");    

}
print ("\n");

print "Inline links, goes with the text \n";

opendir(INFILE, "images") || die ("Unable to open directory");
#this line gets rid of . and ..<br>
@files = grep !/^\./, readdir(INFILE);

closedir(INFILE);

foreach $file (sort @files) {


print ("![$file][$file]\n");  
}
