#!/bin/bash

# Thunar create action dialog
# Name: Resize images exact to .tiff
# Description: Resize to tiff, exact pixel size no aspect ratio enter like: 150x150
# Command: /home/boban/.config/Thunar/custom_actions/image_resize_exact_tiff %N
 
DEST="./images"
mkdir -p $DEST

# Resize 512x512\! = explicit; -resize 512x512^ -gravity center -extent 512x512 = crop and fill; Add a border to the images

EXT=`zenity --title="Resize image exact to .tiff" --entry --text="Enter the image size you want eg. 150x150"`

for file
    do
    if [ ! -e $file ]
        then
        continue
    fi
    to_name="$DEST/"$(echo $file | cut -f1 -d.)".tiff"
    convert -geometry $EXT\! -quality 100 "${file}" "${to_name}"
done


